### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by athas** [bh107/homebrew-bohrium#1]
`brew install bh107/homebrew-bohrium/bohrium` produces the following error:

```
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:211 (message):
No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
/usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindOpenMP.cmake:487 (find_package_handle_standard_args)
ve/openmp/CMakeLists.txt:27 (find_package)
```

Full error log: http://lpaste.net/3928457537401126912

**Comment by omegahm** [comment]
Thanks @Athas. I have an automated system that builds Bohrium every night from this formula, however, it does it with `--HEAD` as well (to test the newest code from Github). Since we haven't updated the version number on Bohrium in a while, the formula in Homebrew is quite old at this time.

I have just updated it and this issue should be fixed with 1258068b343bd8b41100d7cbaef69b189103a1e6.

Can I get you to try again?

**Comment by athas** [comment]
It builds now, but it does not seem to have installed the Python wrapper.  I guess it's not part of the formula (in accordance with Homebrew policy, but as an unofficial tap, you don't have to care).  If so, it may be a good idea for the caveats-section to not just list how to get the Python wrapper.

I tried doing a `pip install --user bohrium` afterwards, but it installed what seems to be some Linux shared objects into my `~/Library/Python/2.7/lib/python/site-packages/bohrium`.

**Comment by athas** [comment]
After [RTFM](http://bohrium.readthedocs.io/installation/osx.html), I installed Cython first, and now it seems to work.  I had to install Cython globally (without passing `--user` to `pip`), though.

**Comment by athas** [comment]
Another thing that should be documented.  This is what happens if I try to use Bohrium with the default Python:

```
$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bohrium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/bohrium/__init__.py", line 24, in <module>
    from .contexts import *
  File "/usr/local/lib/python2.7/site-packages/bohrium/contexts.py", line 7, in <module>
    from . import backend_messaging as messaging
  File "/usr/local/lib/python2.7/site-packages/bohrium/backend_messaging.py", line 6, in <module>
    from ._bh import message as _backend_msg
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/bohrium/_bh.so, 2): Library not loaded: @rpath/libbhc.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/bohrium/_bh.so
  Reason: image not found
```

I need to use the Homebrew-installed Python (`/usr/local/Cellar/python/2.7.14_3/bin/python2.7`) to get it to work.
